samples: "config/female_samples.tsv"

fastp:
  average_qual: 30
  cut_mean_quality: 30
  length_required: 50
  n_base_limit: 1
  extra: "--overrepresentation_analysis" 

star: 
  out_samattributes: "Standard"
  out_samtype: "BAM SortedByCoordinate"
  out_samunmapped: "Within KeepPairs" 
  multimap_nmax: 10
  mismatch_nmax: 10
  # do we want the index and genome in same directory for this?
  star_ref_path: "/hpcfs/users/a1627307/genome/STAR/GRCh38_y_masked"
  extra: 


featureCounts:
  minQual: 1
  minOverlap: 35
  fracOverlap: 0.9
  strandedness: 1
  extra: "-p -B -M --fraction"
  gtf: "/hpcfs/user/a1627307/genome/gencode.v45.primary_assembly.annotation.gtf"

samtools:
  extra:

