samples: "config/female_samples.tsv"

fastp:
  average_qual: 30
  cut_mean_quality: 30
  length_required: 50
  n_base_limit: 1
  extra: "--overrepresentation_analysis" 

star: 
  out_samattributes: "Standard"
  out_samtype: "BAM SortedByCoordinate"
  out_samunmapped: "Within KeepPairs" #unsuure if we want 'keep pairs'
  multimap_nmax: 10
  mismatch_nmax: 10
  star_ref_path: "/hpcfs/user/a1627307/genome"
  extra: 

